//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsundoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsundoku.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book(s) in stack.
        /// </summary>
        internal static string BooksInStack {
            get {
                return ResourceManager.GetString("BooksInStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate(s).
        /// </summary>
        internal static string Certificate_s_ {
            get {
                return ResourceManager.GetString("Certificate(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this book from the stack?.
        /// </summary>
        internal static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this certificate?.
        /// </summary>
        internal static string DeleteCert {
            get {
                return ResourceManager.GetString("DeleteCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this book from the stack..
        /// </summary>
        internal static string FailToDeleteBook {
            get {
                return ResourceManager.GetString("FailToDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to issue certificate of your completion of this book..
        /// </summary>
        internal static string FailToIssueCert {
            get {
                return ResourceManager.GetString("FailToIssueCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use this app.
        /// </summary>
        internal static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.To stack books, go to &quot;Register&quot; and register books..
        /// </summary>
        internal static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. To see the stacked books, back to &quot;Stack&quot; and pull down to refresh..
        /// </summary>
        internal static string Instruction2 {
            get {
                return ResourceManager.GetString("Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. When you&apos;ve read a book, swiping left the book and tap the tick icon in it. The certificate of your completion of this book is issued..
        /// </summary>
        internal static string Instruction3 {
            get {
                return ResourceManager.GetString("Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. To see the certificates, go to &quot;Certificate&quot; and pull down to refresh..
        /// </summary>
        internal static string Instruction4 {
            get {
                return ResourceManager.GetString("Instruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN Code Reader.
        /// </summary>
        internal static string ISBNReader {
            get {
                return ResourceManager.GetString("ISBNReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load offerings.
        /// </summary>
        internal static string LoadOfferings {
            get {
                return ResourceManager.GetString("LoadOfferings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly subscription for.
        /// </summary>
        internal static string MonthlySubFor {
            get {
                return ResourceManager.GetString("MonthlySubFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code doesn&apos;t contain 13 characters..
        /// </summary>
        internal static string NonIsbn13 {
            get {
                return ResourceManager.GetString("NonIsbn13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not subscribing is highly recomended.
        /// </summary>
        internal static string PayWallSubTitle {
            get {
                return ResourceManager.GetString("PayWallSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack more than 10 books!.
        /// </summary>
        internal static string PayWallTitle {
            get {
                return ResourceManager.GetString("PayWallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read date:.
        /// </summary>
        internal static string ReadDate {
            get {
                return ResourceManager.GetString("ReadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        internal static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book stacked successfully.
        /// </summary>
        internal static string StackedBook {
            get {
                return ResourceManager.GetString("StackedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stack the book.
        /// </summary>
        internal static string StackedBookFailed {
            get {
                return ResourceManager.GetString("StackedBookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ISBN Code.
        /// </summary>
        internal static string TypeIsbn {
            get {
                return ResourceManager.GetString("TypeIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
